config/routes.rb
Billing::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :products do 
    collection do
      get 'code_autocomplete'
      get 'products_list'
    end
  end 
  resources :bills  
  root :to => "bills#new"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :billitems

  def new_item(item)
    self.billitems.create({product_id:item[:id], price:item[:price], quant:item[:quantity]})
  end
end

app/models/billitem.rb
class Billitem < ActiveRecord::Base
  belongs_to :bill
  has_one :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :billitems
  def self.sell(item)
    prod = self.find(item[:id])
    prod.update_attributes({price:item[:price], quantity:(prod.quantity - item[:quantity].to_i)})
    prod
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def new
    @bill = Bill.new
    @billitem = Billitem.new
  end

  def create
    @bill= Bill.create
    items = params[:billitems]
    items.each do |item|
      item = item[1] # array of objects turned to hash with the index as the key. The value is the actual object
      @bill.new_item(item)
      Product.sell(item)
    end
    if @bill.save!
      render :json => {success:true}
    end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  http_basic_authenticate_with :name => "theshop", :password => "theshop", :except => [:code_autocomplete, :products_list]

  def code_autocomplete
    @items = Product.where('code like ?', params[:term].upcase+"%")
    items = []
    @items.each {|i|
    items << {label:i.code, id:i.id, code:i.code, name:i.name, price:i.price}
    }
    render :json => items
  end

  def index
    @products = Product.all
  end

  def products_list
    @products = Product.all
  end

  def update
    @product = Product.find(params[:product][:id])
    if @product.update_attributes(params[:product])
      render :json => {success:true, product:@product}
    else
      render :json => {success:false}
    end
  end

  def create
    @product = Product.where({code:params[:product][:code].upcase}).first()
    if @product.nil? 
      params[:product][:code] = params[:product][:code].upcase
      product = Product.create(params[:product])
      render :json => {success:true, product:product}
    else
      render :json => {success:false, msg:"Save failed : Product already exists, edit it from the product database."} 
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    render :json => {success:true}
  end

  def show
    render :json => {success:true, product:Product.find(params[:id])}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/bills/new.html.erb
<div class='container'>
  <ul class='nav nav-pills'>
    <li class="active">
    <%= link_to "Bill", new_bill_path %>
    </li>
    <li>
    <%= link_to "Products list", products_list_products_path %>
    </li>
    <li>
    <%= link_to "Products management", products_path %>
    </li>
  </ul>
</div>
<div class="container">
  <form id="bill_item_form">
    <input type="hidden" class="item" id="item_id"></input>
    <input type="text" id="code" placeholder="Code" class="code_autocomplete item"></input>
    <input type="text" id="name" placeholder="Name" class="item" ></input>
    <input type="text" id="price" placeholder="Price" class="item"></input>
    <input type="text" id="quant" placeholder="Quantity" class="item"></input>
    <div class="btn-group">
      <a href="#" class="btn btn-warning" id="reset_billitem"><i class="icon-trash"></i>Reset</a>
      <a href="#" class="btn btn-success" id="add_item_2_bill"><i class="icon-plus-sign"></i>Add</a>
    </div>
  </form>
  <hr\>
  <h2>Bill area</h2>
  <div class="bill_section">
    <div id="bill_area">
      
    </div>

    <div class="btn-group">
      <a href="" class="btn btn-warning" id="reset_bill"><i class="icon-trash"></i>Clear</a>
      <a href="" class="btn btn-success" id="add_bill"><i class="icon-plus-sign"></i>Save</a>
    </div>
    <span id="total"><h2>Total : <strong></strong></h2></span>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Billing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/products/_product.html.erb
<span class="product span12">
  <span class="span1 list-id"><%=product.id%></span>
  <span class="span1 list-code"><%=product.code%></span>
  <span class="span3 list-name"><%=product.name%></span>
  <span class="span1 list-price"><%=product.price%></span>
  <span class="span1 list-quantity"><%=product.quantity%></span>
  <a class="span1 list_item_edit" id="<%= product.id %>"><i class="icon-edit"></i></a>
</span>

app/views/products/index.html.erb
<div class='container'>
  <ul class='nav nav-pills'>
    <li>
    <%= link_to "Bill", new_bill_path %>
    </li>
    <li>
    <%= link_to "Products list", products_list_products_path %>
    </li>
    <li class="active">
    <%= link_to "Products management", products_path %>
    </li>
  </ul>
</div>
<div class="container">
  <div id="new_product">
    <form id="new_product_form">
      <input type="text" id="p_code" placeholder="Code" class="item"></input>
      <input type="text" id="p_name" placeholder="Name" class="item" ></input>
      <input type="text" id="p_price" placeholder="Price" class="item"></input>
      <input type="text" id="p_quant" placeholder="Quantity" class="item"></input>
      <div class="btn-group">
        <a href="" class="btn btn-warning" id="reset_new_product"><i class="icon-trash"></i>Reset</a>
        <a href="" class="btn btn-success" id="add_to_products"><i class="icon-plus-sign"></i>Add</a>
      </div>
    </form>
  </div>

  <span class="span12">
    <span class="span1">Id</span>
    <span class="span1">Code</span>
    <span class="span3">Name</span>
    <span class="span1">Price</span>
    <span class="span1">Quantity</span>
    <span class="span1"><i class="icon-edit"></i>Edit</span>
  </span>
  <br/>
  <hr></hr>
  <div id="products_list">
    <%= render :partial => 'product', :collection => @products %>

  </div>
</div>
<div class="modal" id="modalEdit"></div>

app/views/products/products_list.html.erb
<div class='container'>
  <ul class='nav nav-pills'>
    <li>
      <%= link_to "Bill", new_bill_path %>
    </li>
    <li class="active">
      <%= link_to "Products list", products_list_products_path%>
    </li>
    <li>
      <%= link_to "Products management", products_path %>
    </li>
  </ul>
</div>
<div class="container">
<% @products.each do |product|%>
  <span class="product span12">
    <span class="span2 list-code"><%=product.code%></span>
    <span class="span3 list-name"><%=product.name%></span>
    <span class="span2 list-price"><%=product.price%></span>
    <span class="span1 list-quantity"><%=product.quantity%></span>
  </span>
<%end%>
</div>